version: "3.3"
services:
  transmission:
    image: amitie10g/megafuse
    environment:
      - PUID=<PUID>
      - PGID=<PGID>
      - USERNAME=<MEGA username>
      - PASSWORD=<MEGA password>
      - APIKEY=<Mega API key>
    volumes:
      - <path to data>:/config
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
